baseURL = ''
languageCode = 'en-us'

title = "hello JmSu" 
theme = "lynx"


enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Jm Su"
  headline = ""
  image = "imgs/logo.jpeg"
  links = [
    { blog = { href = "https://blog.jmsu.me", text = "View My Blog", icon="blog" } },
    { blog = { href = "https://sociology.jmsu.me", text = "View My Sociology Posts" } },
    { app = { href = "hcc/", text = "Hobby Card Collection APP", target = "_self", icon=" " } },
    { skku = { href = "https://github.com/Huigz/marp-theme-skku", text = "Marp Theme SKKU" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true